add language to include wildcard search feature
hashicorp/terraform-docs-common pull request #181
Opened 2022-10-19 16:54 UTC by laurenolivia

### What

### Why

### Screenshots

----------

### Merge Checklist
_If items do not apply to your changes, add (N/A) and mark them as complete._

#### Pull Request
- [ ] One or more labels describe the type of change (e.g. clarification) and associated product (e.g. tfc).
- [ ] Description links to related pull requests or issues, if any.

#### Content
- [ ] Redirects have been added for moved, renamed, or deleted pages. This requires a separate PR in the [`terraform-website` repository](https://github.com/hashicorp/terraform-website) `redirects.next.js` file.
- [ ] API documentation and the API Changelog have been updated. 
- [ ] Links to related content where appropriate (e.g., API endpoints, permissions, etc.).
- [ ] Pages with related content are updated and link to this content when appropriate.
- [ ] Sidebar navigation files have been updated for added, deleted, reordered, or renamed pages.
- [ ] New pages have metadata (page name and description) at the top.
- [ ] New images are 2048 px wide. They have HashiCorp standard annotation color (#F92672) and format (rectangle with rounded corners), blurred sensitive details (e.g. credentials, usernames, user icons), and descriptive alt text in the markdown for accessibility.
- [ ] New code blocks have the correct syntax and line breaks to eliminate horizontal scroll bars.
- [ ] UI elements (button names, page names, etc.) are bolded.
- [ ] The Vercel website preview successfully deployed.

#### Reviews
- [ ] I or someone else reviewed the content for technical accuracy.
- [ ] I or someone else reviewed the content for typos, punctuation, spelling, and grammar.

2022-10-19 16:56 UTC, laurenolivia commented
@mgarrell777 hi, again! I added [this](https://github.com/hashicorp/terraform-docs-common/pull/181/files#diff-8b054ac3ec31732ea17d915c8b932001e013947745dd6645ed72b837303f757eR701) entry. Looks like I am carrying along a few other fixes in this PR. Happy to do so, but not sure how this happened.

2022-10-19 17:09 UTC, mgarrell777 approved these changes
@laurenolivia Thanks very much for your effort on this PR. Looks good to me.

2022-10-21 18:59 UTC, brandonc requested changes

2022-10-21 18:59 UTC, brandonc commented on website/docs/cloud-docs/api-docs/workspaces.mdx
> +| `search[wildcard-name]`| **Optional.** If specified, restricts results to workspaces with partial matching. For example, `search[wildcard-name]=*-prod` returns all workspaces ending in `-prod`.
I think we'd better exhaustively describe the kinds of wildcards work (only the ones starting or ending with *)

2022-10-24 17:19 UTC, brandonc approved these changes

2022-10-24 17:20 UTC, merged