add note to indicate that auto-apply has been enabled for run triggers
hashicorp/terraform-docs-common pull request #377
Opened 2023-06-22 20:39 UTC by Uk1288

### What
Update docs to indicate support of auto-apply for run triggers

### Why

### Screenshots
<img width="639" alt="Screenshot 2023-06-22 at 4 35 55 PM" src="https://github.com/hashicorp/terraform-docs-common/assets/22062046/0b103bd7-91fd-4463-a2ff-1d13f058ffc4">

----------

### Merge Checklist
_If items do not apply to your changes, add (N/A) and mark them as complete._

#### Pull Request
- [ ] One or more labels describe the type of change (e.g. clarification) and associated product (e.g. tfc).
- [ ] Description links to related pull requests or issues, if any.

#### Content
- [ ] Redirects have been added for moved, renamed, or deleted pages. This requires a separate PR in the [`terraform-website` repository](https://github.com/hashicorp/terraform-website) `redirects.next.js` file.
- [ ] API documentation and the API Changelog have been updated. 
- [ ] Links to related content where appropriate (e.g., API endpoints, permissions, etc.).
- [ ] Pages with related content are updated and link to this content when appropriate.
- [ ] Sidebar navigation files have been updated for added, deleted, reordered, or renamed pages.
- [ ] New pages have metadata (page name and description) at the top.
- [ ] New images are 2048 px wide. They have HashiCorp standard annotation color (#F92672) and format (rectangle with rounded corners), blurred sensitive details (e.g. credentials, usernames, user icons), and descriptive alt text in the markdown for accessibility.
- [ ] New code blocks have the correct syntax and line breaks to eliminate horizontal scroll bars.
- [ ] UI elements (button names, page names, etc.) are bolded.
- [ ] The Vercel website preview successfully deployed.

#### Reviews
- [ ] I or someone else reviewed the content for technical accuracy.
- [ ] I or someone else reviewed the content for typos, punctuation, spelling, and grammar.

2023-08-09 22:05 UTC, uturunku1 requested changes
<img width="688" alt="Screenshot 2023-08-09 at 3 04 01 PM" src="https://github.com/hashicorp/terraform-docs-common/assets/21225410/4ff8e6e8-7539-4708-9220-50c04068af62">
I was noticing the sentences for the changelog start in present tense. Aside from this change, I am ready to approve this PR!

2023-08-09 22:05 UTC, uturunku1 commented on website/docs/cloud-docs/api-docs/changelog.mdx
> +* Updated [Workspaces API](/terraform/cloud-docs/api-docs/workspaces) to support `auto-apply-run-trigger` attribute which controls whether run trigger runs should be auto applied.
```suggestion
* Update [Workspaces API](/terraform/cloud-docs/api-docs/workspaces) to support `auto-apply-run-trigger` attribute which controls whether run trigger runs should be auto applied.
```

2023-08-21 16:46 UTC, brandonc commented on website/docs/cloud-docs/workspaces/settings/run-triggers.mdx
> +~> **Important:** Runs initiated in your workspace as the result of a run trigger connection to a source workspace may auto-apply depending on your [auto-apply-run-trigger](/terraform/cloud-docs/work
I found the message itself softened from "will never auto-apply" to "may auto-apply" but the severity went from "note" to "important"-- I think we should explain the interaction here but I also think there's nothing unexpected that needs a callout box.

```suggestion
## Run Triggers Auto-Apply Setting

Runs initiated by run trigger will not auto-apply unless the [auto-apply-run-trigger](/terraform/cloud-docs/workspaces/settings#run-triggers) setting is enabled. This setting operates independently of the workspace [auto-apply](/terraform/cloud-docs/workspaces/settings#auto-apply-and-manual-apply) setting.
```

2023-10-31 21:30 UTC, rkoron007 approved these changes
Small suggestions for style, but this looks great to me! As always, feel free to push back on anything that doesn't feel good to you ✨

2023-10-31 21:30 UTC, rkoron007 commented on website/docs/cloud-docs/api-docs/workspaces.mdx
> +| `data.attributes.auto-apply-run-trigger`      | boolean | `false`   | Whether to automatically apply changes when a Terraform plan is successful in runs initiated by run triggers. Not yet supported
We only talk about present tense in docs, so we don't need the "yet":
```suggestion
| `data.attributes.auto-apply-run-trigger`      | boolean | `false`   | Whether to automatically apply changes when a Terraform plan is successful in runs initiated by run triggers. Not supported in Terraform Enterprise.                                                                                                                                                                                                                                                                                                   |
```

2023-10-31 21:30 UTC, rkoron007 commented on website/docs/cloud-docs/api-docs/workspaces.mdx
> +| `data.attributes.auto-apply-run-trigger`      | boolean        | (previous value) | Whether to automatically apply changes when a Terraform plan is successful in runs initiated by run triggers. Not
Same as above:
```suggestion
| `data.attributes.auto-apply-run-trigger`      | boolean        | (previous value) | Whether to automatically apply changes when a Terraform plan is successful in runs initiated by run triggers. Not supported in Terraform Enterprise.                                                                                                                                                                                                                                                                                                    |
```

2023-10-31 21:30 UTC, rkoron007 commented on website/docs/cloud-docs/workspaces/settings/index.mdx
> +In addition to the main auto-apply setting (which affects runs created by the UI, API, CLI, and version control webhooks), Terraform Cloud also has a separate setting for runs created by [run trigger
I think this flows slightly better as two sentences:
```suggestion
The main auto-apply setting affects runs created by the Terraform Cloud user interface, API, CLI, and version control webhooks. Terraform Cloud also has a separate setting for runs created by [run triggers](/terraform/cloud-docs/workspaces/settings/run-triggers) from another workspace.
```

2023-10-31 21:30 UTC, rkoron007 commented on website/docs/cloud-docs/workspaces/settings/run-triggers.mdx
> +Runs initiated by run trigger will not auto-apply unless the "Auto-apply run triggers" setting is enabled. This setting operates independently of the primary workspace [auto-apply](/terraform/cloud-d
I'm assuming the UI actually says "Auto-apply run triggers"? If so then we can bold it like so:
```suggestion
Runs initiated by a run trigger do not auto-apply unless you enable the **Auto-apply run triggers** setting. This setting operates independently of the primary workspace [auto-apply](/terraform/cloud-docs/workspaces/settings#auto-apply) setting.
```

2023-10-31 21:33 UTC, merged