Display module tests generation as an org setting
hashicorp/terraform-docs-common pull request #483
Opened 2023-10-23 20:44 UTC by sebasslash

### What
Add brief details on module test generation in both the organization settings page and publishing modules page.

### Why

### Screenshots

----------

### Merge Checklist
_If items do not apply to your changes, add (N/A) and mark them as complete._

#### Pull Request
- [ ] One or more labels describe the type of change (e.g. clarification) and associated product (e.g. tfc).
- [ ] Description links to related pull requests or issues, if any.

#### Content
- [ ] Redirects have been added to `website/redirects.js` for moved, renamed, or deleted pages.
- [ ] API documentation and the API Changelog have been updated. 
- [ ] Links to related content where appropriate (e.g., API endpoints, permissions, etc.).
- [ ] Pages with related content are updated and link to this content when appropriate.
- [ ] Sidebar navigation files have been updated for added, deleted, reordered, or renamed pages.
- [ ] New pages have metadata (page name and description) at the top.
- [ ] New images are 2048 px wide. They have HashiCorp standard annotation color (#F92672) and format (rectangle with rounded corners), blurred sensitive details (e.g. credentials, usernames, user icons), and descriptive alt text in the markdown for accessibility.
- [ ] New code blocks have the correct syntax and line breaks to eliminate horizontal scroll bars.
- [ ] UI elements (button names, page names, etc.) are bolded.
- [ ] The Vercel website preview successfully deployed.

#### Reviews
- [ ] I or someone else reviewed the content for technical accuracy.
- [ ] I or someone else reviewed the content for typos, punctuation, spelling, and grammar.

2023-10-26 00:46 UTC, nfagerlund requested changes
This mostly hits the right notes! I suggest splitting it up a little, and caught one or two glitches.

2023-10-26 00:46 UTC, nfagerlund commented on website/docs/cloud-docs/registry/publish-modules.mdx
> +You will be able to generate tests for your module once a version has been published. Tests can only be generated once per module and are intended to be reviewed by the module's authors before being
- I suggest putting a bit of lead-in context here — one of the things that rarely gets stated with this project is that these tests are meant to be run with `terraform test`.
- Wrong anchor link on the second one there.
- This is a permission, not a setting, right? Or is there an additional org-wide setting I'm forgetting about? 

```suggestion
You can generate tests for your module, and can run the resulting tests with [the `terraform test` command](/terraform/cli/commands/test).

Before you can generate tests for a module, it must have at least one version published. Tests can only be generated once per module and are intended to be reviewed by the module's authors before being checked into version control and maintained with the rest of the module's content. If the module's configuration files exceed 128KB in total size, Terraform Cloud will not be able to generate tests for that module.

You must have [permission to manage registry modules](/terraform/cloud-docs/users-teams-organizations/permissions#manage-private-registry) and [permission to manage module test generation](/terraform/cloud-docs/users-teams-organizations/permissions#manage-module-test-generation-beta) in order to generate tests.
```

2023-10-26 19:06 UTC, nfagerlund approved these changes

2023-10-27 16:24 UTC, Uk1288 approved these changes

2023-10-27 16:27 UTC, merged